version: '3'

services:
  postgres:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_DB: 'head_db'
      POSTGRES_USER: 'headb'
      POSTGRES_PASSWORD: 'headb'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

volumes:
  postgres-data:
